image: node:18

variables:
  # Explicitly define CI_SERVER_URL
  CI_SERVER_URL: "https://newgit.computools.org"

pages:
  cache:
    paths:
      - documentation/node_modules/
  script:
    - cd documentation
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - documentation/public
  only:
    - main
    - doc-web-site
